id: A8C4635C8
title: A Yearning Song of Prayer to Invoke the Wisdom Mind of the Compassionate Teacher
  Padmasambhava
type: translation
pechas:
- IBFA51D73
- IFC1C3870
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:46.296426
  last_modified_at: 2023-01-04 11:52:46.296438
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  IBFA51D73/0B41: 71F9
  IFC1C3870/EB94: 71F9
